# Generated by Django 5.0.6 on 2026-06-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer_country_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_sent', to='dashboard.matchmaker'),
        ),
    ]
